CREATE TABLE IF NOT EXISTS bot_groups (
 chat_id BIGINT PRIMARY KEY, title VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS users (
 user_id BIGINT PRIMARY KEY, username VARCHAR(64) NOT NULL DEFAULT '', display_name VARCHAR(255) NOT NULL DEFAULT '', is_bot BOOLEAN NOT NULL DEFAULT FALSE,
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX idx_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS group_settings (
 chat_id BIGINT PRIMARY KEY, settings JSON NOT NULL, updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS group_members (
 chat_id BIGINT NOT NULL, user_id BIGINT NOT NULL, role VARCHAR(32) NOT NULL DEFAULT 'member',
 joined_at DATETIME(6) NULL, verified_at DATETIME(6) NULL, left_at DATETIME(6) NULL, message_count BIGINT NOT NULL DEFAULT 0,
 PRIMARY KEY(chat_id,user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS list_entries (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, chat_id BIGINT NOT NULL DEFAULT 0, user_id BIGINT NOT NULL DEFAULT 0,
 username VARCHAR(64) NOT NULL DEFAULT '', kind VARCHAR(16) NOT NULL, reason VARCHAR(500) NOT NULL DEFAULT '', created_by BIGINT NOT NULL,
 expires_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 UNIQUE KEY uk_entry(chat_id,user_id,username,kind), INDEX idx_list_user(user_id,chat_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS keyword_rules (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, chat_id BIGINT NOT NULL, keyword VARCHAR(500) NOT NULL, match_type VARCHAR(32) NOT NULL,
 reply_type VARCHAR(32) NOT NULL, content TEXT NOT NULL, priority INT NOT NULL DEFAULT 0, enabled BOOLEAN NOT NULL DEFAULT TRUE,
 reply BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX idx_keywords(chat_id,priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS verification_sessions (
 token VARCHAR(48) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY, chat_id BIGINT NOT NULL, user_id BIGINT NOT NULL, challenge_type VARCHAR(16) NOT NULL,
 question VARCHAR(255) NOT NULL, answer_hash CHAR(64) NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'pending', attempts INT NOT NULL DEFAULT 0,
 fail_action VARCHAR(16) NOT NULL, expires_at DATETIME(6) NOT NULL, prompt_id BIGINT NOT NULL DEFAULT 0, kick_started BOOLEAN NOT NULL DEFAULT FALSE,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), verified_at DATETIME(6) NULL,
 next_attempt_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), recovery_attempts INT NOT NULL DEFAULT 0, last_error VARCHAR(500) NOT NULL DEFAULT '',
 INDEX idx_verification_expiry(status,expires_at), INDEX idx_verification_member(chat_id,user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS moderation_logs (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, event_key VARCHAR(100) NOT NULL UNIQUE, chat_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
 message_id BIGINT NOT NULL, message_text TEXT NOT NULL, risk_score INT NOT NULL, matched_rules JSON NOT NULL, ai_result JSON NULL,
 decision JSON NOT NULL, source VARCHAR(32) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX idx_moderation_chat(chat_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS punishments (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, event_key VARCHAR(100) NOT NULL UNIQUE, chat_id BIGINT NOT NULL, user_id BIGINT NOT NULL, message_id BIGINT NOT NULL,
 decision JSON NOT NULL, source VARCHAR(32) NOT NULL, actor_id BIGINT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'pending',
 deleted BOOLEAN NOT NULL DEFAULT FALSE, acted BOOLEAN NOT NULL DEFAULT FALSE, last_error VARCHAR(500) NOT NULL DEFAULT '',
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 INDEX idx_punishments_user(chat_id,user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ai_usage_logs (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, chat_id BIGINT NOT NULL, model VARCHAR(255) NOT NULL, input_tokens INT NOT NULL DEFAULT 0,
 output_tokens INT NOT NULL DEFAULT 0, latency_ms BIGINT NOT NULL, cached BOOLEAN NOT NULL, result VARCHAR(32) NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX idx_ai_chat(chat_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS admin_audits (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, chat_id BIGINT NOT NULL, actor_id BIGINT NOT NULL, action VARCHAR(64) NOT NULL,
 old_value JSON NULL, new_value JSON NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX idx_admin_chat(chat_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS feedback (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, log_id BIGINT NOT NULL, actor_id BIGINT NOT NULL, note VARCHAR(500) NOT NULL,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uk_feedback(log_id,actor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS update_inbox (
 update_id BIGINT PRIMARY KEY, partition_id BIGINT NOT NULL, payload JSON NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'pending',
 attempts INT NOT NULL DEFAULT 0, available_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), lease_until DATETIME(6) NULL,
 last_error VARCHAR(500) NOT NULL DEFAULT '', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 INDEX idx_inbox_pending(status,available_at), INDEX idx_inbox_partition(partition_id,status,update_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS bot_state (name VARCHAR(64) PRIMARY KEY, value BIGINT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
