CREATE TABLE IF NOT EXISTS system_settings (
 id TINYINT PRIMARY KEY,
 value_encrypted MEDIUMTEXT NOT NULL,
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
